/** Short feature chips — keep in sync with README. */
export const FEATURES = [
	'SvelteKit native',
	'No Kit patches',
	'SSR islands',
	'Server islands',
	'Route weaving',
	'Lakes',
	'Partials',
	'Live partials',
	'Shared objects',
	'Cross-island context',
	'Continuity',
	'Island composition',
	'Content collections',
	'~7.6 KB runtime',
	'load · idle · visible · interaction',
	'Media queries',
	'Remote functions',
	'Async Svelte',
	'Form actions',
	'SPA router',
	'View Transitions',
	'Link prefetch',
	'Keep layout',
	'devalue props',
	'Import attributes',
	'Named presets',
	'Nesting',
	'Prerender',
	'Snippets',
	'csr=false HMR'
] as const;
